version: 0.1
            
phases:
  pre_build:
    install: 
      commands:
        - aws --version
        - echo Logging into Amazon ECr
        - $(aws ecr get-login --no-include-email $AWS_DEFAULT_REGION)
    build:
      commands:
        - echo Build started on 'date'
        - echo Building Docker image
        - if [ -z "$IMAGE_TAG" ]; then IMAGE_TAG=latest; fi
        - if [ -n "$CODEBUILD_RESOLVED_SOURCE_VERSION" ]; then IMAGE_TAG="$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)"; fi
        - echo Using image tag "$IMAGE_TAG"
        - IMAGE_URI="$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME"
        - echo Building image...
        - docker build -t $IMAGE_URI:latest .
        - echo Tagging image with tag "$IMAGE_TAG"...
        - docker tag tag $IMAGE_URI:latest $IMAGE_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image to uri "$IMAGE_URI"...
      - docker push $IMAGE_URI:latest
      - docker push $IMAGE_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"%s","imageUri":"%s"}]' "$IMAGE_REPO_NAME" "$IMAGE_URI:$IMAGE_TAG" > images.json
  artifacts:
    files:
      - images.json