version: 0.1
            
phases:
  pre_build:
    install: 
      commands:
        - go get -u github.com/golang/lint/golint
    pre_build: 
      commands:
        - echo.Logging in to Amazon ECR...
        - aws --version
        - $(aws ecr get-login --no-include-email --region ap-southeast-2)
        - docker buld -t hellogo .
    build:
      commands:
        - echo Build started on 'date'
        - echo Building Docker image
        - docker build -t $REPOSITORY_URI:latest .   
        - docker tag hellogo:latest 438991312594.dkr.ecr.ap-southeast-2.amazonaws.com/hellogo:latest
    post_build:
      commands:
        - echo Build completed on 'date'
        - echo Pushing the Docker image
        - docker push 438991312594.dkr.ecr.ap-southeast-2.amazonaws.com/hellogo:latest
    artifacts:
      files:
        - imageDetail.json